---

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - gettext
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - mcrypt
  - nmap
  - node
  - watchman
  - yarn
  - nvm
  - ssh-copy-id
  - readline
  - openssl
  - wget
  - npm


homebrew_taps:
  - homebrew/core
  - caskroom/cask


homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
