---

- name: HomeBrew Installation
  shell: >
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        creates=/usr/local/Cellar
  become: no


- name: Ensure Homebrew is installed.
  git:
    repo: "{{ homebrew_repo }}"
    version: master
    dest: "{{ homebrew_install_path }}"
    update: no
    accept_hostkey: yes
    depth: 1

- name: Ensure configured homebrew packages are installed.
  homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: present
  become: no
  with_items: "{{ homebrew_installed_packages }}"


- name: Linking Npm/Node
  command: "brew link --overwrite node"
  become: no  


# Cask applications installation
#- name: Install configured cask applications.
#  homebrew_cask:
#    name: "{{ item }}"
#    state: present
#    install_options: "appdir={{ homebrew_cask_appdir }}"
#  with_items: "{{ homebrew_cask_apps }}"


- name: Installing React Native Cli Using NPM
  command: "npm install -g react-native-cli"



